stages:          # List of stages for jobs, and their order of execution
  - build
  - push

before_script:
    - echo "Logging into Quay.io" 
    - docker login quay.io -u ${QUAY_USER} -p ${QUAY_PASS}

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building image..."
    - make docker-build IMG="quay.io/dekelly/codecoapp-acm:latest"
    - echo "Build complete."

push-job:   # This job runs in the push stage.
  stage: push   # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Pushing image tyo Quay.io..."
    - make docker-push IMG="quay.io/dekelly/codecoapp-acm:latest"

  only:
    - main
