stages:
  - build
  - build-cluster
  - test-build
  - test-logs
  - clean-up
  - push

variables: 
  IMG_NAME: "quay.io/dekelly/codecoapp-acm"
  IMG_TAG: "${CI_COMMIT_SHORT_SHA}"
  IMG: "$IMG_NAME:$IMG_TAG"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # Disable Docker TLS

  # KUSTOMIZE_VERSION: 5.0.3 # Define the desired kustomize version
  # KUBECONFIG: ~/.kube/config

services:
    - name: docker:dind
      command: ["--privileged"] 

before_script:
  - dnf install -y wget make git dnf-plugins-core
  - dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
  - dnf install -y docker-ce-cli
  - wget https://go.dev/dl/go1.21.9.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.21.9.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
  - export PATH=$PATH:$(go env GOPATH)/bin
  - echo "Logging into Quay..."
  - echo "$QUAY_PASS" | docker login quay.io -u "$QUAY_USER" --password-stdin
  - echo "Logging into Docker"
  - docker login -u $DOCK_USER -p $DOCK_PASS

  # - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
  # - mv ./kustomize /usr/local/bin/kustomize  # Move it to a location in PATH
  # - chmod +x ./scripts/pre_deploy.sh ./scripts/post_deploy.sh


build:
  stage: build
  image: fedora:latest
  services:
    - name: docker:dind
      command: ["--privileged"]  # Enable privileged mode
  script:
    - docker info  # Check Docker connection
    - controller-gen object paths=./api/...  # Generate controller object files
    - docker build -t ${IMG} .  # Build Docker image
    - echo "Build complete."

build-cluster:
  stage: build-cluster
  image: fedora:latest
  services:
    - name: docker:dind
      command: ["--privileged"]  # Enable privileged mode
  script:
    - export PATH=$PATH:/usr/local/go/bin
    - echo "Installing Kind and kubectl..."
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - curl -Lo ./kubectl https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo "Creating Kind cluster..."
    - kind create cluster --config ./config/cluster/kind-config.yaml
    - echo "Test cluster created."

test-build:
  stage: test-build
  image: fedora:latest
  services:
    - name: docker:dind
      command: ["--privileged"]  # Enable privileged mode
  script:
    - echo "Running tests..."
    - ./scripts/pre_deploy.sh  # Run pre-deployment script
    # - cd config/manager && kustomize edit set image controller=$IMG  # Set the controller image in the Kustomize file
    # - kustomize build config/default | kubectl apply -f -  # Build and deploy using kubectl
    # - ./scripts/post_deploy.sh 

    # - kubectl create -f codecosampleapp
    # - sleep 60

    # - kubectl get po - - if status = FAILED, get name of pod status FAILED, kubectl describe pod POD_NAME, loop through all status fails

test-logs:
  stage: test-logs
  image: fedora:latest
  services:
    - name: docker:dind
      command: ["--privileged"]
  script:
    - sleep 30
    - kubectl get po -A

clean-up: 
    stage: clean-up
    image: fedora:latest
    services:
      - name: docker:dind
        command: ["--privileged"]  # Enable privileged mode
    script:
      - echo "Deleting cluster ..."
      - kind delete cluster

    

# Further stages like test and push can be uncommented and configured as needed.

# test:
#   stage: test
#   tags:
#     - acm-runner
#   image: golang:1.21   # Or use an image with kubectl/kind pre-installed
#   services:
#     - docker:dind
#   before_script:
#     # Install kubectl
#     - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#     - chmod +x ./kubectl
#     - mv ./kubectl /usr/local/bin/kubectl
#     # Install Kind
#     - curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
#     - chmod +x ./kind
#     - mv ./kind /usr/local/bin/kind
#     # Create a Kubernetes cluster with Kind
#     - kind create cluster --config $KIND_CONFIG
#     # Set kubeconfig for kubectl
#     - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
#   script:
#     # Build the operator's container image (or use pre-built)
#     - echo "Deploying operator..."
#     - make docker-build IMG="pipeline-build:v0.0.1"
#     # Wait for the operator deployment to be ready
#     - make deploy IMG="pipeline-build:v0.0.1"
#     # Check if the operator pod is running successfully
#     - sleep 120
#     - kubectl get pods

push:
   stage: push
   image: fedora:latest
   services:
     - name: docker:dind
       command: ["--privileged"]
   variables:
     DOCKER_TLS_CERTDIR: ""
   script:
     - export PATH=$PATH:/usr/local/go/bin
     - echo "Pushing image named $IMG to Quay.io..."
     - docker info  # Check if the Docker daemon is running
     - docker push "${IMG}"
     - echo "Push complete"
   only:
     - rht-integration

integration_build:
  stage: integration_build
  image: docker:26.1.2
  services:
    - docker:26.1.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: $CI_REGISTRY_IMAGE/integration
    IMAGE_TAG: 2.0.1
  only:
    - integration
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building docker image with CODECO requirements"
    - git clone https://gitlab.eclipse.org/eclipse-research-labs/codeco-project/gitlab-profile.git
    - docker build -t $CI_REGISTRY_IMAGE/integration:2.0.1 -f gitlab-profile/Dockerfile-integration .
    - docker push $CI_REGISTRY_IMAGE/integration:2.0.1 # pushing to intermediate private repository

integration:
  stage: integration
  image: docker:26.1.2
  services:
    - docker:26.1.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: $CI_REGISTRY_IMAGE/integration
    IMAGE_TAG: 2.0.1
  only:
    - integration
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker rm integ --force
    - docker rmi $CI_REGISTRY_IMAGE/integration:2.0.1
  script:
    - |
      docker run -t -v /var/run/docker.sock:/var/run/docker.sock -e DOCKERHUB_USER=$DOCKERHUB_USER -e DOCKERHUB_PASS=$DOCKERHUB_PASS --network host --name integ --rm $CI_REGISTRY_IMAGE/integration:2.0.1 bash -c -i "
    
      git clone https://gitlab.eclipse.org/eclipse-research-labs/codeco-project/acm.git 

      kind delete cluster
      kind create cluster --config ./acm/config/cluster/kind-config.yaml

      cd acm
      echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      make docker-build docker-push IMG=$DOCKERHUB_USER/codecoapp-operator:2.0.0
      make deploy IMG=$DOCKERHUB_USER/codecoapp-operator:2.0.0

      kubectl apply -f ./config/samples/codeco_v1alpha1_codecoapp_ver3.yaml

      # Wait for 20 minutes, if Codeco Application Pods are not running, then the test is Failed!
      # Note that the kubectl wait command will continue the script execution earlier than the timeout if the condition is satisfied
      if kubectl wait --for=condition=Ready pod --all -n he-codeco-acm --timeout=20m; then 
          echo "Application pods are in Running state"
          kubectl get pods -A; 
          exit 0; # success
      else
          kubectl get pods -A; 
          exit 1; # error
      fi

      # Verify that all CODECO pods are in the Running state, or else, fail the test
      if kubectl wait --for=condition=Ready pod --all --all-namespaces --timeout=20m; then 
          echo "Application pods are in Running state"
          kubectl get pods -A; 
          exit 0; # success
      else
          kubectl get pods -A; 
          exit 1; # error
      fi

      # [In-progress] Other integration tests: Verify correct input and output for every codeco component

      "




