stages:
  - build
  - push
  - test

variables: 
  IMG_NAME: "quay.io/dekelly/codecoapp-acm"
  IMG_TAG: "${CI_COMMIT_SHORT_SHA}"
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - dnf install -y wget make git dnf-plugins-core
  - dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
  - dnf install -y docker-ce-cli
  - wget https://go.dev/dl/go1.21.9.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.21.9.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
  - export PATH=$PATH:$(go env GOPATH)/bin
  - echo "Logging into Quay..."
  - docker login quay.io -u $QUAY_USER -p $QUAY_PASS

build:
  stage: build
  image: fedora:latest
  script:
    - export PATH=$PATH:/usr/local/go/bin
    - echo "Building image..."
    - make docker-build IMG="$IMG_NAME:$IMG_TAG"
    - echo "Build complete."

push:
  stage: push
  image: fedora:latest
  script:
    - export PATH=$PATH:/usr/local/go/bin
    - echo "Pushing image to Quay.io..."
    - make docker-push IMG="$IMG_NAME:$IMG_TAG"
  only:
    - main

test:
  stage: test
  image: fedora:latest
  script:
    - export PATH=$PATH:/usr/local/go/bin
    - echo "Installing Kind and kubectl..."
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - curl -Lo ./kubectl https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo "Creating Kind cluster..."
    - kind create cluster --config ./acm/config/cluster/kind-config.yaml
    - echo "Deploying operator..."
    - kubectl apply -f codeco_v1alpha_codecoapp_ver3.yaml
    - echo "Waiting for pods to be running..."
    - timeout=180
    - interval=10
    - end=$((SECONDS+timeout))
    - while [ $SECONDS -lt $end ]; do
        kubectl get po -A | grep -q 'Running' && break;
        sleep $interval;
      done
    - echo "Checking pod statuses..."
    - failed_pods=$(kubectl get po -A --field-selector=status.phase=Failed | wc -l)
    - if [ "$failed_pods" -gt 1 ]; then
        echo "More than 1 pod has failed. Failing the test stage.";
        kubectl get po -A --field-selector=status.phase=Failed -o custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | tail -n +2 | while read -r pod namespace; do
          echo "Logs for pod $pod in namespace $namespace:";
          kubectl logs -n $namespace $pod;
        done;
        exit 1;
      fi
  dependencies:
    - push
