---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - codeco.he-codeco.eu
  resources:
  - codecoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - codeco.he-codeco.eu
  resources:
  - codecoapps/finalizers
  verbs:
  - update
- apiGroups:
  - codeco.he-codeco.eu
  resources:
  - codecoapps/status
  verbs:
  - get
  - patch
  - update
