// SPDX-FileCopyrightText: 2023 Siemens AG
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: solver-service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SolverClient is the client API for Solver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverClient interface {
	Solve(ctx context.Context, in *Request, opts ...grpc.CallOption) (Solver_SolveClient, error)
}

type solverClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverClient(cc grpc.ClientConnInterface) SolverClient {
	return &solverClient{cc}
}

func (c *solverClient) Solve(ctx context.Context, in *Request, opts ...grpc.CallOption) (Solver_SolveClient, error) {
	stream, err := c.cc.NewStream(ctx, &Solver_ServiceDesc.Streams[0], "/Solver/Solve", opts...)
	if err != nil {
		return nil, err
	}
	x := &solverSolveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Solver_SolveClient interface {
	Recv() (*Reply, error)
	grpc.ClientStream
}

type solverSolveClient struct {
	grpc.ClientStream
}

func (x *solverSolveClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SolverServer is the server API for Solver service.
// All implementations must embed UnimplementedSolverServer
// for forward compatibility
type SolverServer interface {
	Solve(*Request, Solver_SolveServer) error
	mustEmbedUnimplementedSolverServer()
}

// UnimplementedSolverServer must be embedded to have forward compatible implementations.
type UnimplementedSolverServer struct {
}

func (UnimplementedSolverServer) Solve(*Request, Solver_SolveServer) error {
	return status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSolverServer) mustEmbedUnimplementedSolverServer() {}

// UnsafeSolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverServer will
// result in compilation errors.
type UnsafeSolverServer interface {
	mustEmbedUnimplementedSolverServer()
}

func RegisterSolverServer(s grpc.ServiceRegistrar, srv SolverServer) {
	s.RegisterService(&Solver_ServiceDesc, srv)
}

func _Solver_Solve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SolverServer).Solve(m, &solverSolveServer{stream})
}

type Solver_SolveServer interface {
	Send(*Reply) error
	grpc.ServerStream
}

type solverSolveServer struct {
	grpc.ServerStream
}

func (x *solverSolveServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

// Solver_ServiceDesc is the grpc.ServiceDesc for Solver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Solver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Solver",
	HandlerType: (*SolverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Solve",
			Handler:       _Solver_Solve_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "solver-service.proto",
}
