// SPDX-FileCopyrightText: 2023 Siemens AG
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package grpc

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Request within kubernetes types, where deepcopy-gen is used.
func (in *Request) DeepCopyInto(out *Request) {
	p := proto.Clone(in).(*Request)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Request. Required by controller-gen.
func (in *Request) DeepCopy() *Request {
	if in == nil {
		return nil
	}
	out := new(Request)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Request. Required by controller-gen.
func (in *Request) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Reply within kubernetes types, where deepcopy-gen is used.
func (in *Reply) DeepCopyInto(out *Reply) {
	p := proto.Clone(in).(*Reply)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reply. Required by controller-gen.
func (in *Reply) DeepCopy() *Reply {
	if in == nil {
		return nil
	}
	out := new(Reply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Reply. Required by controller-gen.
func (in *Reply) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
