apiVersion: codeco.he-codeco.eu/v1alpha1
kind: CodecoApp
metadata:
  name: codecoappinstance3
spec:
  appEnergyLimit: "20" # Maximum desired level of energy expenditure for the overall k8s infrastructure associated with an application (percent)
  appFailureTolerance: "" # Desired tolerance to infrastructure failures, High/Medium/Low
  appName: "acm-swm-app"
  codecoapp-msspec:
  - serviceName: "database"
    podspec:
      containers:
      - name: postgres-db
        image: postgres:13
        ports:
        - containerPort: 5432
          name: "postgres"
        env:
        - name: POSTGRES_DB
          value: vehicle_quotes
        - name: POSTGRES_USER
          value: vehicle_quotes
        - name: POSTGRES_PASSWORD
          value: password
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
    requiredResources:
      cpu: "50" # percentage
      mem: "8" # GB
      nwbandwidth: "1.2" #Mbs
      nwlatency: "3" # Ms
    serviceChannels:
    - chanelName: ""
      advancedChannelSettings:
        bandwidth: "5"
        frameSize: "100"
        maxDelay: "1"
        sendInterval: "10"
      otherService:
        appName: "acm-swm-app"
        port: 0
        serviceName: "front-end"
  - serviceName: "front-end"
    podspec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
    requiredResources:
      cpu: "50" # percentage
      mem: "8" # GB
      nwbandwidth: "1.2" #Mbs
      nwlatency: "3" # Ms
    serviceChannels:
    - chanelName: "fe-db-channel"
      advancedChannelSettings:
        bandwidth: "5"
        frameSize: "100"
        maxDelay: "1"
        sendInterval: "10"
      otherService:
        appName: "acm-swm-app"
        port: 0
        serviceName: "database"
  complianceClass: "High" #expected level of compliance, based on a scale - High, Medium, Low
  qosClass: "Gold" # Preferred QoS level, Gold, Silver, BestEffort
  securityClass: "Good" #Desired level of security for the application, based on a likert scale, 5 levels -HIGH-GOOD-MEDIUM-LOW-NONE
