apiVersion: codeco.he-codeco.eu/v1alpha1
kind: CodecoApp
metadata:
  labels:
    app.kubernetes.io/name: codecoapp2
    app.kubernetes.io/instance: codecoapp-sample
    app.kubernetes.io/part-of: codecoapp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: codecoapp-operator
  name: codecoapp-sample
spec:
  name: My CODECO App
  qosclass: Dev
  codecoapp-msspec: [
    {
      name: "CODECO micro service 1",
      podspecname: "MicroService1",
      required-resources: {
        cpu-usage-pct: 200,
        mem-usage-GB: 120,
        nwbandwidth-Mbs: 10
      }
    },
    {
      name: "CODECO micro service 2",
      podspecname: "MicroService2",
      required-resources: {
        cpu-usage-pct: 150,
        mem-usage-GB: 80,
        nwbandwidth-Mbs: 20
      }
    },
  ]  
  # TODO(user): Add fields here
