apiVersion: v1
kind: Service
metadata:
  name: codeco-gui-backend-service
  labels:
    app: codeco-gui-backend
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: codeco-gui-backend
