apiVersion: v1
kind: ServiceAccount
metadata:
  name: codeco-gui-backend
  labels:
    app: codeco-gui-backend
    component: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codeco-gui-backend
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["codeco.he-codeco.eu"]
  resources: ["codecoapps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codeco-gui-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codeco-gui-backend
subjects:
- kind: ServiceAccount
  name: codeco-gui-backend
  namespace: he-codeco-acm