apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    # role: record-rules
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
  - name: example
    rules:
    - record: code:prometheus_http_requests_total:sum #metric name
      expr: "sum by (code) (prometheus_http_requests_total)" #metric value
    - record: sum_container_cpu_utilization
      expr: "sum(rate(container_cpu_usage_seconds_total[5m]))"
      # Average CPU usage over the past 5 minutes for each instance (node)
    - record: avgNodeCpu
      expr: avg(node_cpu_seconds_total) by (instance)
    - record: avgNodeMemory
      expr: avg(node_memory_MemAvailable_bytes) by (instance)