# Copyright (c) 2024 Red Hat, Inc
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0
# 
# Contributors:
#     [name] - [contribution]

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: codecoapp-status-metrics
    # role: record-rules
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
  - name: codecoapp-status-metrics
    rules:
      # Average CPU utilization for each instance (node)
    - record: instance:node_cpu:rate1m #metric name
      expr: avg by (instance) (1 - rate(node_cpu_seconds_total{mode="idle"}[1m])) #metric value
      # Average node memory
    - record: instance:node_memory:avg1m
      expr: avg_over_time(node_memory_MemTotal_bytes[1m]) - (avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m]))
      # Average node energy
    - record: instance:node_energy:irate1m
      expr: avg by (instance) (irate(kepler_node_platform_joules_total{mode="dynamic"}[1m]))
      # Average node failure
    - record: instance:node_status:avg1m
      expr: sum(avg_over_time(kube_node_status_condition{condition="Ready", status!="true"}[1m])) by (node)
      # Node info
    - record: instance:node_info:current
      expr: kube_node_info
      # Pod info
    - record: pod:pod_info:current
      expr: kube_pod_info
      # Average CPU utilization for each pod
    - record: pod:container_cpu:rate1m
      expr: avg by (pod) (rate(container_cpu_usage_seconds_total[1m]))
      # Average memory usage for each pod 
    - record: pod:container_memory:avg1m
      expr: avg by (pod) (avg_over_time(container_memory_usage_bytes[1m]))
      # Average CPU utlization for each application
    - record: app:container_cpu:rate1m
      expr: avg(rate(container_cpu_usage_seconds_total[1m]))
      # Average memory usage for each application 
    - record: app:container_memory:avg1m
      expr: sum(avg_over_time(container_memory_usage_bytes[1m]))