---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <app-name> #Name that identifies the service (can be the same as <service-name>)
  name: <service-name>
  namespace: <service-namespace>
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: <metrics-port> #Port where metrics are exposed
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: <app-name>