---
apiVersion: v1
kind: Service
metadata:
  labels:
    label1: <label1>
    label2: <label2>
    .
    .
    .
  name: <service-name>
  namespace: <service-namespace>
spec:
  ports:
  - name: http-metrics
    port: <metrics-port> #Port where metrics are exposed
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/name: <app-name>